// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(wick_ffiFFI)
import wick_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_wick_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_wick_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWickFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Streaming sink for decode output. Foreign callers implement this
 * trait (Kotlin class, Swift class, Python subclass) and pass an
 * `Arc<dyn ModalitySink>` to [`Session::generate_streaming`] to
 * receive tokens + audio frames + the finish reason as they happen.
 *
 * All methods are required from foreign implementations (UniFFI 0.28
 * foreign traits don't carry Rust's default-impl fallbacks). Callers
 * that don't care about a modality can provide an empty body.
 *
 * Threading: every method is invoked on the same Rust thread running
 * `generate` — the decode thread. If the foreign runtime requires
 * marshalling onto a different thread (e.g. Swift's `@MainActor`) it
 * is the implementer's responsibility to dispatch the call there.
 */
public protocol ModalitySink: AnyObject, Sendable {
    
    /**
     * Called with each chunk of generated token IDs. Ownership of the
     * `Vec<u32>` is transferred to the callback, so implementations
     * may retain or store it directly if needed — no clone required.
     */
    func onTextTokens(tokens: [UInt32]) 
    
    /**
     * Called with each chunk of generated PCM audio samples. Not
     * called for text-only models; LFM2-Audio-class models emit here.
     * The `sample_rate` is the model's native output rate (typically
     * 24000 for LFM2-Audio) and is stable across the whole generate
     * call.
     */
    func onAudioFrames(pcm: [Float], sampleRate: UInt32) 
    
    /**
     * Called exactly once per [`Session::generate_streaming`] call,
     * as the last thing before the wrapper returns. Fires for both
     * success (`MaxTokens`, `Stop`, `Cancelled`, `ContextFull`) and
     * failure paths: on error the wrapper synthesizes a
     * [`FinishReason::Error`] so foreign consumers have a reliable
     * end-of-stream signal regardless of how the call exits.
     */
    func onDone(reason: FinishReason) 
    
}
/**
 * Streaming sink for decode output. Foreign callers implement this
 * trait (Kotlin class, Swift class, Python subclass) and pass an
 * `Arc<dyn ModalitySink>` to [`Session::generate_streaming`] to
 * receive tokens + audio frames + the finish reason as they happen.
 *
 * All methods are required from foreign implementations (UniFFI 0.28
 * foreign traits don't carry Rust's default-impl fallbacks). Callers
 * that don't care about a modality can provide an empty body.
 *
 * Threading: every method is invoked on the same Rust thread running
 * `generate` — the decode thread. If the foreign runtime requires
 * marshalling onto a different thread (e.g. Swift's `@MainActor`) it
 * is the implementer's responsibility to dispatch the call there.
 */
open class ModalitySinkImpl: ModalitySink, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wick_ffi_fn_clone_modalitysink(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wick_ffi_fn_free_modalitysink(handle, $0) }
    }

    

    
    /**
     * Called with each chunk of generated token IDs. Ownership of the
     * `Vec<u32>` is transferred to the callback, so implementations
     * may retain or store it directly if needed — no clone required.
     */
open func onTextTokens(tokens: [UInt32])  {try! rustCall() {
    uniffi_wick_ffi_fn_method_modalitysink_on_text_tokens(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokens),$0
    )
}
}
    
    /**
     * Called with each chunk of generated PCM audio samples. Not
     * called for text-only models; LFM2-Audio-class models emit here.
     * The `sample_rate` is the model's native output rate (typically
     * 24000 for LFM2-Audio) and is stable across the whole generate
     * call.
     */
open func onAudioFrames(pcm: [Float], sampleRate: UInt32)  {try! rustCall() {
    uniffi_wick_ffi_fn_method_modalitysink_on_audio_frames(
            self.uniffiCloneHandle(),
        FfiConverterSequenceFloat.lower(pcm),
        FfiConverterUInt32.lower(sampleRate),$0
    )
}
}
    
    /**
     * Called exactly once per [`Session::generate_streaming`] call,
     * as the last thing before the wrapper returns. Fires for both
     * success (`MaxTokens`, `Stop`, `Cancelled`, `ContextFull`) and
     * failure paths: on error the wrapper synthesizes a
     * [`FinishReason::Error`] so foreign consumers have a reliable
     * end-of-stream signal regardless of how the call exits.
     */
open func onDone(reason: FinishReason)  {try! rustCall() {
    uniffi_wick_ffi_fn_method_modalitysink_on_done(
            self.uniffiCloneHandle(),
        FfiConverterTypeFinishReason_lower(reason),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceModalitySink {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceModalitySink = UniffiVTableCallbackInterfaceModalitySink(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeModalitySink.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ModalitySink: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeModalitySink.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ModalitySink: handle missing in uniffiClone")
            }
        },
        onTextTokens: { (
            uniffiHandle: UInt64,
            tokens: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeModalitySink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onTextTokens(
                     tokens: try FfiConverterSequenceUInt32.lift(tokens)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onAudioFrames: { (
            uniffiHandle: UInt64,
            pcm: RustBuffer,
            sampleRate: UInt32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeModalitySink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onAudioFrames(
                     pcm: try FfiConverterSequenceFloat.lift(pcm),
                     sampleRate: try FfiConverterUInt32.lift(sampleRate)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDone: { (
            uniffiHandle: UInt64,
            reason: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeModalitySink.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDone(
                     reason: try FfiConverterTypeFinishReason_lift(reason)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceModalitySink> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceModalitySink>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitModalitySink() {
    uniffi_wick_ffi_fn_init_callback_vtable_modalitysink(UniffiCallbackInterfaceModalitySink.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModalitySink: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ModalitySink>()

    typealias FfiType = UInt64
    typealias SwiftType = ModalitySink

    public static func lift(_ handle: UInt64) throws -> ModalitySink {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ModalitySinkImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ModalitySink) -> UInt64 {
         if let rustImpl = value as? ModalitySinkImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModalitySink {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ModalitySink, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModalitySink_lift(_ handle: UInt64) throws -> ModalitySink {
    return try FfiConverterTypeModalitySink.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModalitySink_lower(_ value: ModalitySink) -> UInt64 {
    return FfiConverterTypeModalitySink.lower(value)
}






/**
 * Stateful inference handle. Wraps [`wick::Session`] behind a
 * `Mutex` so UniFFI's `Arc<Session>` shape works with methods that
 * need `&mut self` on the inner session (prefill, generate, reset).
 *
 * Call [`WickEngine::new_session`] to open a session; the engine's
 * `Arc<Model>` and `Arc<BpeTokenizer>` are cloned into the new
 * session so it outlives the engine handle across FFI calls.
 */
public protocol SessionProtocol: AnyObject, Sendable {
    
    /**
     * Append raw text to the context, running a prefill over just
     * the new tokens. `EmptyInput` error if `text` is empty.
     */
    func appendText(text: String) throws 
    
    /**
     * Append pre-tokenized IDs. Useful when the caller has its own
     * tokenizer + chat-template pipeline.
     */
    func appendTokens(tokens: [UInt32]) throws 
    
    /**
     * Signal in-flight `generate()` to exit with
     * `FinishReason::Cancelled` at the next between-token check.
     * Safe from any thread. No-op if no `generate()` is running.
     */
    func cancel() 
    
    /**
     * Capabilities reported by the loaded model. Cheap — reads a
     * cached copy, no lock.
     */
    func capabilities()  -> ModalityCapabilities
    
    /**
     * Run autoregressive decode and return all emitted tokens +
     * a summary. Synchronous — the call blocks until the decode
     * loop exits (`max_tokens`, EOS, `cancel()`, or error).
     *
     * For streaming (per-chunk delivery) and async, see the PR 4 /
     * PR 5 follow-ups in `wick-ffi/README.md`.
     */
    func generate(opts: GenerateOpts) throws  -> GenerateOutput
    
    /**
     * Async variant of [`Session::generate`] — runs buffered decode
     * (returning every emitted token + a summary) on a tokio blocking
     * worker so the caller's async context isn't stalled by the
     * synchronous decode loop.
     *
     * Cancellation: dropping the returned future (Kotlin coroutine
     * scope exit, Swift `Task.cancel`, Python `asyncio.Task.cancel`)
     * triggers both an abort of the queued `spawn_blocking` task (so
     * a not-yet-started decode never runs) and a
     * [`Session::cancel`] call (so an in-flight decode exits at its
     * next between-token check with [`FinishReason::Cancelled`]).
     * Either path releases the session mutex; subsequent calls see
     * a clean session. You can also call [`Session::cancel`]
     * directly from any thread to trigger the same in-flight exit
     * without dropping the future. See [`AsyncCancelGuard`] for the
     * full rationale.
     *
     * On error the wrapper performs the same poisoned-mutex handling
     * as sync [`Session::generate`]. `JoinError` from a panic in the
     * blocking closure surfaces as [`FfiError::Backend`] with a
     * diagnostic prefix.
     */
    func generateAsync(opts: GenerateOpts) async throws  -> GenerateOutput
    
    /**
     * Run autoregressive decode, streaming every token (and audio
     * frame, for audio-capable models) to a foreign [`ModalitySink`]
     * as soon as it's produced. Returns only a [`GenerateSummary`] —
     * token IDs are delivered through `sink.on_text_tokens`, not a
     * return value.
     *
     * Synchronous: the call blocks on the decode thread and each
     * `sink` method runs on that same thread before decoding
     * continues. For async, see PR 5 in `wick-ffi/README.md`.
     *
     * **Callback reentrancy — deadlock hazard.** The session mutex is
     * held for the entire call, and sink callbacks run while that
     * lock is held. Calling back into methods that also take the
     * mutex ([`Session::append_text`], [`Session::append_tokens`],
     * [`Session::generate`], [`Session::generate_streaming`],
     * [`Session::reset`]) from inside a sink method will deadlock.
     * [`Session::cancel`] and [`Session::position`] are atomic-backed
     * and safe to call from the sink or from any other thread.
     *
     * Cancellation: call [`Session::cancel`] from any thread (or from
     * inside a sink callback on this thread) to terminate the loop at
     * the next between-token check; `sink.on_done` fires with
     * [`FinishReason::Cancelled`].
     *
     * End-of-stream guarantee: `sink.on_done` fires exactly once per
     * call, even on error paths. If the underlying decode returns an
     * error before reaching its own `on_done` call (e.g.,
     * `EmptyInput` with no prefill logits), the wrapper synthesizes
     * a terminal `on_done(FinishReason::Error { message })` so
     * foreign consumers have a reliable end-of-stream signal
     * regardless of how the call exits.
     */
    func generateStreaming(opts: GenerateOpts, sink: ModalitySink) throws  -> GenerateSummary
    
    /**
     * Async variant of [`Session::generate_streaming`] — delivers
     * tokens and audio frames to the foreign [`ModalitySink`] as the
     * decode loop produces them, from within a blocking worker so
     * the caller's async runtime stays responsive.
     *
     * Sink callbacks run on the blocking worker thread that's
     * executing the decode — **not** on the caller's async thread.
     * The reentrancy hazard documented on
     * [`Session::generate_streaming`] still applies: sink callbacks
     * that call back into `append_text` / `generate*` / `reset` from
     * inside the session will deadlock on the session mutex.
     * [`Session::cancel`] and [`Session::position`] remain atomic-
     * backed and safe to invoke from any thread (including from
     * inside a callback).
     *
     * Cancellation: dropping the returned future fires the same
     * abort + [`Session::cancel`] pair as [`Session::generate_async`]
     * (see [`AsyncCancelGuard`]). For an in-flight decode, the loop
     * exits with [`FinishReason::Cancelled`] and the sink's `on_done`
     * fires on the blocking worker before the task completes —
     * foreign consumers get the terminal signal even though they've
     * already stopped awaiting. For a queued-but-not-started decode,
     * abort cancels the task without ever running the closure; no
     * sink callbacks fire for that case (the decode never began).
     */
    func generateStreamingAsync(opts: GenerateOpts, sink: ModalitySink) async throws  -> GenerateSummary
    
    /**
     * Current KV position — how many tokens live in the cache.
     * Atomic-backed; safe to call from a different thread while
     * `generate()` is in flight.
     */
    func position()  -> UInt32
    
    /**
     * Drop cached state + resample the seed. After `reset()` the
     * session behaves like a freshly-opened one (same
     * model/tokenizer/config, no accumulated context).
     *
     * Returns `Result` so a poisoned-mutex case surfaces as an error
     * instead of panicking across the FFI boundary.
     */
    func reset() throws 
    
}
/**
 * Stateful inference handle. Wraps [`wick::Session`] behind a
 * `Mutex` so UniFFI's `Arc<Session>` shape works with methods that
 * need `&mut self` on the inner session (prefill, generate, reset).
 *
 * Call [`WickEngine::new_session`] to open a session; the engine's
 * `Arc<Model>` and `Arc<BpeTokenizer>` are cloned into the new
 * session so it outlives the engine handle across FFI calls.
 */
open class Session: SessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wick_ffi_fn_clone_session(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wick_ffi_fn_free_session(handle, $0) }
    }

    

    
    /**
     * Append raw text to the context, running a prefill over just
     * the new tokens. `EmptyInput` error if `text` is empty.
     */
open func appendText(text: String)throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_method_session_append_text(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * Append pre-tokenized IDs. Useful when the caller has its own
     * tokenizer + chat-template pipeline.
     */
open func appendTokens(tokens: [UInt32])throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_method_session_append_tokens(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt32.lower(tokens),$0
    )
}
}
    
    /**
     * Signal in-flight `generate()` to exit with
     * `FinishReason::Cancelled` at the next between-token check.
     * Safe from any thread. No-op if no `generate()` is running.
     */
open func cancel()  {try! rustCall() {
    uniffi_wick_ffi_fn_method_session_cancel(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Capabilities reported by the loaded model. Cheap — reads a
     * cached copy, no lock.
     */
open func capabilities() -> ModalityCapabilities  {
    return try!  FfiConverterTypeModalityCapabilities_lift(try! rustCall() {
    uniffi_wick_ffi_fn_method_session_capabilities(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Run autoregressive decode and return all emitted tokens +
     * a summary. Synchronous — the call blocks until the decode
     * loop exits (`max_tokens`, EOS, `cancel()`, or error).
     *
     * For streaming (per-chunk delivery) and async, see the PR 4 /
     * PR 5 follow-ups in `wick-ffi/README.md`.
     */
open func generate(opts: GenerateOpts)throws  -> GenerateOutput  {
    return try  FfiConverterTypeGenerateOutput_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_method_session_generate(
            self.uniffiCloneHandle(),
        FfiConverterTypeGenerateOpts_lower(opts),$0
    )
})
}
    
    /**
     * Async variant of [`Session::generate`] — runs buffered decode
     * (returning every emitted token + a summary) on a tokio blocking
     * worker so the caller's async context isn't stalled by the
     * synchronous decode loop.
     *
     * Cancellation: dropping the returned future (Kotlin coroutine
     * scope exit, Swift `Task.cancel`, Python `asyncio.Task.cancel`)
     * triggers both an abort of the queued `spawn_blocking` task (so
     * a not-yet-started decode never runs) and a
     * [`Session::cancel`] call (so an in-flight decode exits at its
     * next between-token check with [`FinishReason::Cancelled`]).
     * Either path releases the session mutex; subsequent calls see
     * a clean session. You can also call [`Session::cancel`]
     * directly from any thread to trigger the same in-flight exit
     * without dropping the future. See [`AsyncCancelGuard`] for the
     * full rationale.
     *
     * On error the wrapper performs the same poisoned-mutex handling
     * as sync [`Session::generate`]. `JoinError` from a panic in the
     * blocking closure surfaces as [`FfiError::Backend`] with a
     * diagnostic prefix.
     */
open func generateAsync(opts: GenerateOpts)async throws  -> GenerateOutput  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_wick_ffi_fn_method_session_generate_async(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeGenerateOpts_lower(opts)
                )
            },
            pollFunc: ffi_wick_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_wick_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_wick_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeGenerateOutput_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Run autoregressive decode, streaming every token (and audio
     * frame, for audio-capable models) to a foreign [`ModalitySink`]
     * as soon as it's produced. Returns only a [`GenerateSummary`] —
     * token IDs are delivered through `sink.on_text_tokens`, not a
     * return value.
     *
     * Synchronous: the call blocks on the decode thread and each
     * `sink` method runs on that same thread before decoding
     * continues. For async, see PR 5 in `wick-ffi/README.md`.
     *
     * **Callback reentrancy — deadlock hazard.** The session mutex is
     * held for the entire call, and sink callbacks run while that
     * lock is held. Calling back into methods that also take the
     * mutex ([`Session::append_text`], [`Session::append_tokens`],
     * [`Session::generate`], [`Session::generate_streaming`],
     * [`Session::reset`]) from inside a sink method will deadlock.
     * [`Session::cancel`] and [`Session::position`] are atomic-backed
     * and safe to call from the sink or from any other thread.
     *
     * Cancellation: call [`Session::cancel`] from any thread (or from
     * inside a sink callback on this thread) to terminate the loop at
     * the next between-token check; `sink.on_done` fires with
     * [`FinishReason::Cancelled`].
     *
     * End-of-stream guarantee: `sink.on_done` fires exactly once per
     * call, even on error paths. If the underlying decode returns an
     * error before reaching its own `on_done` call (e.g.,
     * `EmptyInput` with no prefill logits), the wrapper synthesizes
     * a terminal `on_done(FinishReason::Error { message })` so
     * foreign consumers have a reliable end-of-stream signal
     * regardless of how the call exits.
     */
open func generateStreaming(opts: GenerateOpts, sink: ModalitySink)throws  -> GenerateSummary  {
    return try  FfiConverterTypeGenerateSummary_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_method_session_generate_streaming(
            self.uniffiCloneHandle(),
        FfiConverterTypeGenerateOpts_lower(opts),
        FfiConverterTypeModalitySink_lower(sink),$0
    )
})
}
    
    /**
     * Async variant of [`Session::generate_streaming`] — delivers
     * tokens and audio frames to the foreign [`ModalitySink`] as the
     * decode loop produces them, from within a blocking worker so
     * the caller's async runtime stays responsive.
     *
     * Sink callbacks run on the blocking worker thread that's
     * executing the decode — **not** on the caller's async thread.
     * The reentrancy hazard documented on
     * [`Session::generate_streaming`] still applies: sink callbacks
     * that call back into `append_text` / `generate*` / `reset` from
     * inside the session will deadlock on the session mutex.
     * [`Session::cancel`] and [`Session::position`] remain atomic-
     * backed and safe to invoke from any thread (including from
     * inside a callback).
     *
     * Cancellation: dropping the returned future fires the same
     * abort + [`Session::cancel`] pair as [`Session::generate_async`]
     * (see [`AsyncCancelGuard`]). For an in-flight decode, the loop
     * exits with [`FinishReason::Cancelled`] and the sink's `on_done`
     * fires on the blocking worker before the task completes —
     * foreign consumers get the terminal signal even though they've
     * already stopped awaiting. For a queued-but-not-started decode,
     * abort cancels the task without ever running the closure; no
     * sink callbacks fire for that case (the decode never began).
     */
open func generateStreamingAsync(opts: GenerateOpts, sink: ModalitySink)async throws  -> GenerateSummary  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_wick_ffi_fn_method_session_generate_streaming_async(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeGenerateOpts_lower(opts),FfiConverterTypeModalitySink_lower(sink)
                )
            },
            pollFunc: ffi_wick_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_wick_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_wick_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeGenerateSummary_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Current KV position — how many tokens live in the cache.
     * Atomic-backed; safe to call from a different thread while
     * `generate()` is in flight.
     */
open func position() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_wick_ffi_fn_method_session_position(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Drop cached state + resample the seed. After `reset()` the
     * session behaves like a freshly-opened one (same
     * model/tokenizer/config, no accumulated context).
     *
     * Returns `Result` so a poisoned-mutex case surfaces as an error
     * instead of panicking across the FFI boundary.
     */
open func reset()throws   {try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_method_session_reset(
            self.uniffiCloneHandle(),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Session

    public static func lift(_ handle: UInt64) throws -> Session {
        return Session(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Session) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Session {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Session, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lift(_ handle: UInt64) throws -> Session {
    return try FfiConverterTypeSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lower(_ value: Session) -> UInt64 {
    return FfiConverterTypeSession.lower(value)
}






/**
 * Owning handle to a loaded model. Mirrors [`wick::WickEngine`];
 * `#[uniffi::Object]` requires `Arc<Self>` wrapping which matches how
 * the underlying engine is already used internally.
 */
public protocol WickEngineProtocol: AnyObject, Sendable {
    
    /**
     * What this model accepts as input / emits as output. Derived at
     * load time from the manifest's `inference_type`.
     */
    func capabilities()  -> ModalityCapabilities
    
    /**
     * Short summary of the loaded model (architecture, vocab size,
     * max context, etc.). Returns a `Clone` of the stored metadata.
     */
    func metadata()  -> ModelMetadata
    
    /**
     * Open a new [`Session`] sharing this engine's model + tokenizer
     * by `Arc` clone. The returned session outlives `&self`; the
     * engine keeps the shared state live for every session it hands
     * out. Cheap — no model load, just config + state allocation.
     */
    func newSession(config: SessionConfig)  -> Session
    
}
/**
 * Owning handle to a loaded model. Mirrors [`wick::WickEngine`];
 * `#[uniffi::Object]` requires `Arc<Self>` wrapping which matches how
 * the underlying engine is already used internally.
 */
open class WickEngine: WickEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_wick_ffi_fn_clone_wickengine(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_wick_ffi_fn_free_wickengine(handle, $0) }
    }

    
    /**
     * Load a model from a local filesystem path. Accepts the same
     * inputs as the native [`wick::WickEngine::from_path`]:
     * a bare `.gguf`, a LeapBundles `.json` manifest, or a directory
     * containing exactly one `.json` manifest.
     *
     * Remote URLs in manifests are rejected in this PR — `BundleRepo`
     * wiring lands when the `remote` feature activates here.
     */
public static func fromPath(path: String, config: EngineConfig)throws  -> WickEngine  {
    return try  FfiConverterTypeWickEngine_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_wick_ffi_fn_constructor_wickengine_from_path(
        FfiConverterString.lower(path),
        FfiConverterTypeEngineConfig_lower(config),$0
    )
})
}
    

    
    /**
     * What this model accepts as input / emits as output. Derived at
     * load time from the manifest's `inference_type`.
     */
open func capabilities() -> ModalityCapabilities  {
    return try!  FfiConverterTypeModalityCapabilities_lift(try! rustCall() {
    uniffi_wick_ffi_fn_method_wickengine_capabilities(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Short summary of the loaded model (architecture, vocab size,
     * max context, etc.). Returns a `Clone` of the stored metadata.
     */
open func metadata() -> ModelMetadata  {
    return try!  FfiConverterTypeModelMetadata_lift(try! rustCall() {
    uniffi_wick_ffi_fn_method_wickengine_metadata(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Open a new [`Session`] sharing this engine's model + tokenizer
     * by `Arc` clone. The returned session outlives `&self`; the
     * engine keeps the shared state live for every session it hands
     * out. Cheap — no model load, just config + state allocation.
     */
open func newSession(config: SessionConfig) -> Session  {
    return try!  FfiConverterTypeSession_lift(try! rustCall() {
    uniffi_wick_ffi_fn_method_wickengine_new_session(
            self.uniffiCloneHandle(),
        FfiConverterTypeSessionConfig_lower(config),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWickEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WickEngine

    public static func lift(_ handle: UInt64) throws -> WickEngine {
        return WickEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WickEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WickEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WickEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWickEngine_lift(_ handle: UInt64) throws -> WickEngine {
    return try FfiConverterTypeWickEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWickEngine_lower(_ value: WickEngine) -> UInt64 {
    return FfiConverterTypeWickEngine.lower(value)
}




/**
 * Per-engine configuration at load time. Mirrors [`wick::EngineConfig`]
 * with `u64` fields (UniFFI doesn't marshal `usize`).
 */
public struct EngineConfig: Equatable, Hashable {
    /**
     * KV-cache capacity in tokens. Capped by the model's own
     * `max_seq_len`. Pass `0` to use the model's full declared
     * `max_seq_len` (translated to `usize::MAX` internally, then
     * capped by the loader).
     */
    public var contextSize: UInt64
    public var backend: BackendPreference

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * KV-cache capacity in tokens. Capped by the model's own
         * `max_seq_len`. Pass `0` to use the model's full declared
         * `max_seq_len` (translated to `usize::MAX` internally, then
         * capped by the loader).
         */contextSize: UInt64, backend: BackendPreference) {
        self.contextSize = contextSize
        self.backend = backend
    }

    

    
}

#if compiler(>=6)
extension EngineConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineConfig {
        return
            try EngineConfig(
                contextSize: FfiConverterUInt64.read(from: &buf), 
                backend: FfiConverterTypeBackendPreference.read(from: &buf)
        )
    }

    public static func write(_ value: EngineConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.contextSize, into: &buf)
        FfiConverterTypeBackendPreference.write(value.backend, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lift(_ buf: RustBuffer) throws -> EngineConfig {
    return try FfiConverterTypeEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineConfig_lower(_ value: EngineConfig) -> RustBuffer {
    return FfiConverterTypeEngineConfig.lower(value)
}


/**
 * Per-call decode options. Mirrors [`wick::GenerateOpts`].
 *
 * `flush_every_tokens` / `flush_every_ms` are accepted but have no
 * effect under the synchronous [`Session::generate`] — they're
 * meaningful once streaming (foreign-trait `ModalitySink`) lands
 * in a follow-up PR. Including them in the record now keeps the FFI
 * surface stable across that transition.
 */
public struct GenerateOpts: Equatable, Hashable {
    public var maxTokens: UInt32
    public var temperature: Float
    public var topP: Float
    public var topK: UInt32
    /**
     * Reserved — the sampler doesn't implement rep-penalty yet.
     */
    public var repetitionPenalty: Float
    /**
     * Early-stop IDs (EOS / instruction markers / end-of-turn).
     */
    public var stopTokens: [UInt32]
    /**
     * Ignored under synchronous generate; reserved for streaming.
     */
    public var flushEveryTokens: UInt32
    /**
     * Ignored under synchronous generate; reserved for streaming.
     */
    public var flushEveryMs: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(maxTokens: UInt32, temperature: Float, topP: Float, topK: UInt32, 
        /**
         * Reserved — the sampler doesn't implement rep-penalty yet.
         */repetitionPenalty: Float, 
        /**
         * Early-stop IDs (EOS / instruction markers / end-of-turn).
         */stopTokens: [UInt32], 
        /**
         * Ignored under synchronous generate; reserved for streaming.
         */flushEveryTokens: UInt32, 
        /**
         * Ignored under synchronous generate; reserved for streaming.
         */flushEveryMs: UInt32) {
        self.maxTokens = maxTokens
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.repetitionPenalty = repetitionPenalty
        self.stopTokens = stopTokens
        self.flushEveryTokens = flushEveryTokens
        self.flushEveryMs = flushEveryMs
    }

    

    
}

#if compiler(>=6)
extension GenerateOpts: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerateOpts: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerateOpts {
        return
            try GenerateOpts(
                maxTokens: FfiConverterUInt32.read(from: &buf), 
                temperature: FfiConverterFloat.read(from: &buf), 
                topP: FfiConverterFloat.read(from: &buf), 
                topK: FfiConverterUInt32.read(from: &buf), 
                repetitionPenalty: FfiConverterFloat.read(from: &buf), 
                stopTokens: FfiConverterSequenceUInt32.read(from: &buf), 
                flushEveryTokens: FfiConverterUInt32.read(from: &buf), 
                flushEveryMs: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: GenerateOpts, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.maxTokens, into: &buf)
        FfiConverterFloat.write(value.temperature, into: &buf)
        FfiConverterFloat.write(value.topP, into: &buf)
        FfiConverterUInt32.write(value.topK, into: &buf)
        FfiConverterFloat.write(value.repetitionPenalty, into: &buf)
        FfiConverterSequenceUInt32.write(value.stopTokens, into: &buf)
        FfiConverterUInt32.write(value.flushEveryTokens, into: &buf)
        FfiConverterUInt32.write(value.flushEveryMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateOpts_lift(_ buf: RustBuffer) throws -> GenerateOpts {
    return try FfiConverterTypeGenerateOpts.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateOpts_lower(_ value: GenerateOpts) -> RustBuffer {
    return FfiConverterTypeGenerateOpts.lower(value)
}


/**
 * Bundle of everything a synchronous `generate` call produces:
 * the generated token IDs plus the decode summary. The two are
 * returned together so callers don't have to manage a separate
 * callback channel; streaming (per-chunk delivery) lands in PR 4.
 */
public struct GenerateOutput: Equatable, Hashable {
    /**
     * Generated token IDs, in order, not including any prompt
     * tokens. Decode with [`wick::tokenizer::BpeTokenizer`] on the
     * Rust side or (once exposed) through a tokenizer handle on the
     * FFI side.
     */
    public var tokens: [UInt32]
    public var summary: GenerateSummary

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Generated token IDs, in order, not including any prompt
         * tokens. Decode with [`wick::tokenizer::BpeTokenizer`] on the
         * Rust side or (once exposed) through a tokenizer handle on the
         * FFI side.
         */tokens: [UInt32], summary: GenerateSummary) {
        self.tokens = tokens
        self.summary = summary
    }

    

    
}

#if compiler(>=6)
extension GenerateOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerateOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerateOutput {
        return
            try GenerateOutput(
                tokens: FfiConverterSequenceUInt32.read(from: &buf), 
                summary: FfiConverterTypeGenerateSummary.read(from: &buf)
        )
    }

    public static func write(_ value: GenerateOutput, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt32.write(value.tokens, into: &buf)
        FfiConverterTypeGenerateSummary.write(value.summary, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateOutput_lift(_ buf: RustBuffer) throws -> GenerateOutput {
    return try FfiConverterTypeGenerateOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateOutput_lower(_ value: GenerateOutput) -> RustBuffer {
    return FfiConverterTypeGenerateOutput.lower(value)
}


/**
 * Decode-run metadata. Mirrors [`wick::GenerateSummary`].
 */
public struct GenerateSummary: Equatable, Hashable {
    public var tokensGenerated: UInt32
    public var promptEvalTokens: UInt32
    public var promptEvalMs: UInt32
    public var decodeMs: UInt32
    public var finishReason: FinishReason

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(tokensGenerated: UInt32, promptEvalTokens: UInt32, promptEvalMs: UInt32, decodeMs: UInt32, finishReason: FinishReason) {
        self.tokensGenerated = tokensGenerated
        self.promptEvalTokens = promptEvalTokens
        self.promptEvalMs = promptEvalMs
        self.decodeMs = decodeMs
        self.finishReason = finishReason
    }

    

    
}

#if compiler(>=6)
extension GenerateSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerateSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerateSummary {
        return
            try GenerateSummary(
                tokensGenerated: FfiConverterUInt32.read(from: &buf), 
                promptEvalTokens: FfiConverterUInt32.read(from: &buf), 
                promptEvalMs: FfiConverterUInt32.read(from: &buf), 
                decodeMs: FfiConverterUInt32.read(from: &buf), 
                finishReason: FfiConverterTypeFinishReason.read(from: &buf)
        )
    }

    public static func write(_ value: GenerateSummary, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.tokensGenerated, into: &buf)
        FfiConverterUInt32.write(value.promptEvalTokens, into: &buf)
        FfiConverterUInt32.write(value.promptEvalMs, into: &buf)
        FfiConverterUInt32.write(value.decodeMs, into: &buf)
        FfiConverterTypeFinishReason.write(value.finishReason, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateSummary_lift(_ buf: RustBuffer) throws -> GenerateSummary {
    return try FfiConverterTypeGenerateSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerateSummary_lower(_ value: GenerateSummary) -> RustBuffer {
    return FfiConverterTypeGenerateSummary.lower(value)
}


/**
 * Modality support flags for a loaded model. Mirrors
 * [`wick::ModalityCapabilities`].
 */
public struct ModalityCapabilities: Equatable, Hashable {
    public var textIn: Bool
    public var textOut: Bool
    public var imageIn: Bool
    public var audioIn: Bool
    public var audioOut: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(textIn: Bool, textOut: Bool, imageIn: Bool, audioIn: Bool, audioOut: Bool) {
        self.textIn = textIn
        self.textOut = textOut
        self.imageIn = imageIn
        self.audioIn = audioIn
        self.audioOut = audioOut
    }

    

    
}

#if compiler(>=6)
extension ModalityCapabilities: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModalityCapabilities: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModalityCapabilities {
        return
            try ModalityCapabilities(
                textIn: FfiConverterBool.read(from: &buf), 
                textOut: FfiConverterBool.read(from: &buf), 
                imageIn: FfiConverterBool.read(from: &buf), 
                audioIn: FfiConverterBool.read(from: &buf), 
                audioOut: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ModalityCapabilities, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.textIn, into: &buf)
        FfiConverterBool.write(value.textOut, into: &buf)
        FfiConverterBool.write(value.imageIn, into: &buf)
        FfiConverterBool.write(value.audioIn, into: &buf)
        FfiConverterBool.write(value.audioOut, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModalityCapabilities_lift(_ buf: RustBuffer) throws -> ModalityCapabilities {
    return try FfiConverterTypeModalityCapabilities.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModalityCapabilities_lower(_ value: ModalityCapabilities) -> RustBuffer {
    return FfiConverterTypeModalityCapabilities.lower(value)
}


/**
 * Short summary of a loaded model. Mirrors [`wick::ModelMetadata`].
 */
public struct ModelMetadata: Equatable, Hashable {
    public var architecture: String
    public var maxSeqLen: UInt32
    public var vocabSize: UInt32
    public var hasChatTemplate: Bool
    public var quantization: String
    /**
     * Mirror of GGUF `tokenizer.ggml.add_bos_token`. Consumers that
     * want to insert a BOS at the head of a raw prompt should honor it.
     */
    public var addBosToken: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(architecture: String, maxSeqLen: UInt32, vocabSize: UInt32, hasChatTemplate: Bool, quantization: String, 
        /**
         * Mirror of GGUF `tokenizer.ggml.add_bos_token`. Consumers that
         * want to insert a BOS at the head of a raw prompt should honor it.
         */addBosToken: Bool) {
        self.architecture = architecture
        self.maxSeqLen = maxSeqLen
        self.vocabSize = vocabSize
        self.hasChatTemplate = hasChatTemplate
        self.quantization = quantization
        self.addBosToken = addBosToken
    }

    

    
}

#if compiler(>=6)
extension ModelMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelMetadata {
        return
            try ModelMetadata(
                architecture: FfiConverterString.read(from: &buf), 
                maxSeqLen: FfiConverterUInt32.read(from: &buf), 
                vocabSize: FfiConverterUInt32.read(from: &buf), 
                hasChatTemplate: FfiConverterBool.read(from: &buf), 
                quantization: FfiConverterString.read(from: &buf), 
                addBosToken: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ModelMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.architecture, into: &buf)
        FfiConverterUInt32.write(value.maxSeqLen, into: &buf)
        FfiConverterUInt32.write(value.vocabSize, into: &buf)
        FfiConverterBool.write(value.hasChatTemplate, into: &buf)
        FfiConverterString.write(value.quantization, into: &buf)
        FfiConverterBool.write(value.addBosToken, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelMetadata_lift(_ buf: RustBuffer) throws -> ModelMetadata {
    return try FfiConverterTypeModelMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelMetadata_lower(_ value: ModelMetadata) -> RustBuffer {
    return FfiConverterTypeModelMetadata.lower(value)
}


/**
 * Per-session configuration. Mirrors [`wick::SessionConfig`].
 */
public struct SessionConfig: Equatable, Hashable {
    /**
     * Cap on total tokens held in KV. `None` → model's default
     * `max_seq_len`.
     */
    public var maxSeqLen: UInt32?
    /**
     * KV cache compression mode.
     */
    public var kvCompression: KvCompression
    /**
     * Pinned-prefix length for Phase-1.5 context shift on overflow.
     * `0` disables shift; overflow returns `ContextOverflow` error.
     */
    public var nKeep: UInt32
    /**
     * Deterministic sampling seed. `None` = fresh entropy per call.
     */
    public var seed: UInt64?
    /**
     * Chunked-prefill ubatch size. `0` = monolithic prefill.
     */
    public var ubatchSize: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Cap on total tokens held in KV. `None` → model's default
         * `max_seq_len`.
         */maxSeqLen: UInt32?, 
        /**
         * KV cache compression mode.
         */kvCompression: KvCompression, 
        /**
         * Pinned-prefix length for Phase-1.5 context shift on overflow.
         * `0` disables shift; overflow returns `ContextOverflow` error.
         */nKeep: UInt32, 
        /**
         * Deterministic sampling seed. `None` = fresh entropy per call.
         */seed: UInt64?, 
        /**
         * Chunked-prefill ubatch size. `0` = monolithic prefill.
         */ubatchSize: UInt32) {
        self.maxSeqLen = maxSeqLen
        self.kvCompression = kvCompression
        self.nKeep = nKeep
        self.seed = seed
        self.ubatchSize = ubatchSize
    }

    

    
}

#if compiler(>=6)
extension SessionConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionConfig {
        return
            try SessionConfig(
                maxSeqLen: FfiConverterOptionUInt32.read(from: &buf), 
                kvCompression: FfiConverterTypeKvCompression.read(from: &buf), 
                nKeep: FfiConverterUInt32.read(from: &buf), 
                seed: FfiConverterOptionUInt64.read(from: &buf), 
                ubatchSize: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SessionConfig, into buf: inout [UInt8]) {
        FfiConverterOptionUInt32.write(value.maxSeqLen, into: &buf)
        FfiConverterTypeKvCompression.write(value.kvCompression, into: &buf)
        FfiConverterUInt32.write(value.nKeep, into: &buf)
        FfiConverterOptionUInt64.write(value.seed, into: &buf)
        FfiConverterUInt32.write(value.ubatchSize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionConfig_lift(_ buf: RustBuffer) throws -> SessionConfig {
    return try FfiConverterTypeSessionConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionConfig_lower(_ value: SessionConfig) -> RustBuffer {
    return FfiConverterTypeSessionConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Compute-backend selector. Mirrors [`wick::BackendPreference`];
 * kept as a separate type so the `wick` crate doesn't carry UniFFI
 * annotations.
 */

public enum BackendPreference: Equatable, Hashable {
    
    /**
     * Probe Metal → GPU → CPU at load time.
     */
    case auto
    case cpu
    /**
     * `wgpu` (Vulkan / Metal / DX12). Requires the `gpu` feature.
     */
    case gpu
    /**
     * Native Metal. Requires the `metal` feature + macOS.
     */
    case metal





}

#if compiler(>=6)
extension BackendPreference: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBackendPreference: FfiConverterRustBuffer {
    typealias SwiftType = BackendPreference

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BackendPreference {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .auto
        
        case 2: return .cpu
        
        case 3: return .gpu
        
        case 4: return .metal
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BackendPreference, into buf: inout [UInt8]) {
        switch value {
        
        
        case .auto:
            writeInt(&buf, Int32(1))
        
        
        case .cpu:
            writeInt(&buf, Int32(2))
        
        
        case .gpu:
            writeInt(&buf, Int32(3))
        
        
        case .metal:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBackendPreference_lift(_ buf: RustBuffer) throws -> BackendPreference {
    return try FfiConverterTypeBackendPreference.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBackendPreference_lower(_ value: BackendPreference) -> RustBuffer {
    return FfiConverterTypeBackendPreference.lower(value)
}



/**
 * Typed error surface for `wick-ffi`. Mirrors [`wick::WickError`] one-
 * to-one so foreign callers can pattern-match on error class (Kotlin
 * `when`, Swift `switch`, Python `match`) instead of string-sniffing
 * a generic message.
 *
 * `Backend` is **not** a silent fallback for unmapped `wick::WickError`
 * variants — the `From<WickError>` impl is exhaustive, so adding a
 * new wick variant breaks compilation here. `Backend` exists solely
 * for FFI-internal errors that have no wick analog: `JoinError` from
 * a panicking `spawn_blocking` task, a poisoned `Session::inner`
 * mutex, 32-bit `u64 → usize` overflow in `EngineConfig::try_from`.
 *
 * Every variant carries the data needed to act on it:
 * `ContextOverflow` exposes `max_seq_len` and `by` so callers can
 * reset or truncate rather than re-reading the message;
 * `UnsupportedInferenceType` exposes the offending value;
 * `Io` preserves the underlying OS error message as a string since
 * `io::Error` isn't UniFFI-marshallable.
 *
 * `#[error(...)]` format strings match `wick::WickError` exactly for
 * every shared variant, so `Display` output is identical whether the
 * error originates from wick directly or routes through the FFI
 * wrapper. Pinned by `ffi_error_display_matches_wick_error_for_every_shared_variant`.
 */
public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The loaded model doesn't support the modality the caller
     * requested (e.g. `append_audio` on a text-only LLM).
     */
    case UnsupportedModality
    /**
     * The manifest's `inference_type` is one wick doesn't recognize
     * at this version. Field carries the offending string.
     */
    case UnsupportedInferenceType(inferenceType: String
    )
    /**
     * A concurrent `generate*` call is already in flight on this
     * session. Rust side guards with a mutex; this surfaces when the
     * FFI detects contention.
     */
    case Busy
    /**
     * The caller (or the cancel-on-drop guard) flipped the cancel
     * atomic. Currently wick's `generate` returns this as a
     * `FinishReason::Cancelled` success rather than an `Err`, but
     * the variant exists so a future `append_tokens` cancel (or
     * similar) can surface typed.
     */
    case Cancelled
    /**
     * The context window is full and the session can't shift to make
     * room (e.g. `n_keep == 0`, TurboQuant caches, or the active
     * model doesn't support rope-shift). `max_seq_len` is the cap
     * that was hit; `by` is the overshoot in tokens.
     */
    case ContextOverflow(maxSeqLen: UInt32, by: UInt32
    )
    /**
     * Input buffer was empty (e.g. `append_text("")`, or decode with
     * no prefill state).
     */
    case EmptyInput
    /**
     * Filesystem / mmap / network error surfaced from wick. The
     * underlying `io::Error` isn't marshallable, so the message is
     * flattened to a string. Callers that need the raw kind should
     * parse the `detail` field or open an issue to request a typed
     * field.
     *
     * Field is named `detail` rather than `message` because UniFFI's
     * 0.31 Kotlin generator emits `class Io(val `message`) : FfiException()`
     * AND `override val message` in the body when the field is literally
     * named `message`, producing a "conflicting declarations" error
     * (the constructor param collides with the inherited
     * `Throwable.message` override). Renaming to `detail` sidesteps
     * the collision.
     *
     * Format string matches `wick::WickError::Io`'s `"io: {0}"` so
     * foreign `.toString()` / `String(describing:)` gives the same
     * output Rust consumers see.
     */
    case Io(detail: String
    )
    /**
     * FFI-internal error with no wick analog: `JoinError` from a
     * panicking `spawn_blocking` task, poisoned `Session::inner`
     * mutex, 32-bit `u64 → usize` overflow in `EngineConfig::try_from`,
     * or `wick::WickError::Backend` routed through the `From` impl.
     * Format string matches `wick::WickError::Backend`'s
     * `"backend: {0}"` — FFI-internal constructors that have already
     * formatted a descriptive message (e.g. "generate_async join
     * error: ...") still read cleanly with the `backend:` label.
     *
     * Field is named `detail` rather than `message` for the same
     * `Throwable.message` collision reason as [`FfiError::Io`].
     */
    case Backend(detail: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .UnsupportedModality
        case 2: return .UnsupportedInferenceType(
            inferenceType: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Busy
        case 4: return .Cancelled
        case 5: return .ContextOverflow(
            maxSeqLen: try FfiConverterUInt32.read(from: &buf), 
            by: try FfiConverterUInt32.read(from: &buf)
            )
        case 6: return .EmptyInput
        case 7: return .Io(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 8: return .Backend(
            detail: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .UnsupportedModality:
            writeInt(&buf, Int32(1))
        
        
        case let .UnsupportedInferenceType(inferenceType):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(inferenceType, into: &buf)
            
        
        case .Busy:
            writeInt(&buf, Int32(3))
        
        
        case .Cancelled:
            writeInt(&buf, Int32(4))
        
        
        case let .ContextOverflow(maxSeqLen,by):
            writeInt(&buf, Int32(5))
            FfiConverterUInt32.write(maxSeqLen, into: &buf)
            FfiConverterUInt32.write(by, into: &buf)
            
        
        case .EmptyInput:
            writeInt(&buf, Int32(6))
        
        
        case let .Io(detail):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(detail, into: &buf)
            
        
        case let .Backend(detail):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(detail, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Why a decode loop exited. Mirrors [`wick::FinishReason`].
 */

public enum FinishReason: Equatable, Hashable {
    
    case maxTokens
    case stop
    case cancelled
    case contextFull
    case error(message: String
    )





}

#if compiler(>=6)
extension FinishReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFinishReason: FfiConverterRustBuffer {
    typealias SwiftType = FinishReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FinishReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .maxTokens
        
        case 2: return .stop
        
        case 3: return .cancelled
        
        case 4: return .contextFull
        
        case 5: return .error(message: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FinishReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .maxTokens:
            writeInt(&buf, Int32(1))
        
        
        case .stop:
            writeInt(&buf, Int32(2))
        
        
        case .cancelled:
            writeInt(&buf, Int32(3))
        
        
        case .contextFull:
            writeInt(&buf, Int32(4))
        
        
        case let .error(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinishReason_lift(_ buf: RustBuffer) throws -> FinishReason {
    return try FfiConverterTypeFinishReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinishReason_lower(_ value: FinishReason) -> RustBuffer {
    return FfiConverterTypeFinishReason.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * KV-cache compression mode. Mirrors [`wick::kv_cache::KvCompression`].
 * `TurboQuant` is honored by the CPU backend only; Metal / GPU ignore
 * the setting and use the f32 path.
 */

public enum KvCompression: Equatable, Hashable {
    
    /**
     * No compression — f32 keys and values (default).
     */
    case none
    /**
     * TurboQuant compression. Both `keys` + `values` true is the
     * production configuration; toggling them individually is
     * primarily for debugging the drift contribution of each side.
     * `seed` drives the per-layer randomized Hadamard rotations.
     */
    case turboQuant(seed: UInt64, keys: Bool, values: Bool
    )





}

#if compiler(>=6)
extension KvCompression: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKvCompression: FfiConverterRustBuffer {
    typealias SwiftType = KvCompression

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KvCompression {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .none
        
        case 2: return .turboQuant(seed: try FfiConverterUInt64.read(from: &buf), keys: try FfiConverterBool.read(from: &buf), values: try FfiConverterBool.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KvCompression, into buf: inout [UInt8]) {
        switch value {
        
        
        case .none:
            writeInt(&buf, Int32(1))
        
        
        case let .turboQuant(seed,keys,values):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(seed, into: &buf)
            FfiConverterBool.write(keys, into: &buf)
            FfiConverterBool.write(values, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKvCompression_lift(_ buf: RustBuffer) throws -> KvCompression {
    return try FfiConverterTypeKvCompression.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKvCompression_lower(_ value: KvCompression) -> RustBuffer {
    return FfiConverterTypeKvCompression.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureWickFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Version string of the `wick-ffi` crate. Useful as a smoke test
 * from the foreign-language side — if this is callable, the binding
 * pipeline works end-to-end.
 */
public func wickFfiVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_wick_ffi_fn_func_wick_ffi_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_wick_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_wick_ffi_checksum_func_wick_ffi_version() != 22410) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_modalitysink_on_text_tokens() != 42733) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_modalitysink_on_audio_frames() != 23377) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_modalitysink_on_done() != 22104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_append_text() != 1419) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_append_tokens() != 33572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_cancel() != 52783) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_capabilities() != 13393) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_generate() != 53155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_generate_async() != 34208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_generate_streaming() != 10461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_generate_streaming_async() != 44699) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_position() != 1234) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_session_reset() != 57393) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_wickengine_capabilities() != 25378) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_wickengine_metadata() != 60987) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_method_wickengine_new_session() != 61697) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_wick_ffi_checksum_constructor_wickengine_from_path() != 41757) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitModalitySink()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWickFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all