// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DOWNLOAD_PROGRESS_SINK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DOWNLOAD_PROGRESS_SINK_METHOD0
typedef void (*UniffiCallbackInterfaceDownloadProgressSinkMethod0)(uint64_t, RustBuffer, uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD0
typedef void (*UniffiCallbackInterfaceModalitySinkMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD1
typedef void (*UniffiCallbackInterfaceModalitySinkMethod1)(uint64_t, RustBuffer, uint32_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODALITY_SINK_METHOD2
typedef void (*UniffiCallbackInterfaceModalitySinkMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DOWNLOAD_PROGRESS_SINK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DOWNLOAD_PROGRESS_SINK
typedef struct UniffiVTableCallbackInterfaceDownloadProgressSink {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceDownloadProgressSinkMethod0 _Nonnull onProgress;
} UniffiVTableCallbackInterfaceDownloadProgressSink;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MODALITY_SINK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MODALITY_SINK
typedef struct UniffiVTableCallbackInterfaceModalitySink {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceModalitySinkMethod0 _Nonnull onTextTokens;
    UniffiCallbackInterfaceModalitySinkMethod1 _Nonnull onAudioFrames;
    UniffiCallbackInterfaceModalitySinkMethod2 _Nonnull onDone;
} UniffiVTableCallbackInterfaceModalitySink;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_BUNDLEREPO
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_BUNDLEREPO
uint64_t uniffi_wick_ffi_fn_clone_bundlerepo(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_BUNDLEREPO
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_BUNDLEREPO
void uniffi_wick_ffi_fn_free_bundlerepo(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_BUNDLEREPO_NEW
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_BUNDLEREPO_NEW
uint64_t uniffi_wick_ffi_fn_constructor_bundlerepo_new(RustBuffer store_dir, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_BUNDLEREPO_WITH_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_BUNDLEREPO_WITH_PROGRESS
uint64_t uniffi_wick_ffi_fn_constructor_bundlerepo_with_progress(RustBuffer store_dir, uint64_t progress, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_BUNDLEREPO_STORE_DIR
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_BUNDLEREPO_STORE_DIR
RustBuffer uniffi_wick_ffi_fn_method_bundlerepo_store_dir(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_DOWNLOADPROGRESSSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_DOWNLOADPROGRESSSINK
uint64_t uniffi_wick_ffi_fn_clone_downloadprogresssink(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_DOWNLOADPROGRESSSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_DOWNLOADPROGRESSSINK
void uniffi_wick_ffi_fn_free_downloadprogresssink(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_INIT_CALLBACK_VTABLE_DOWNLOADPROGRESSSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_INIT_CALLBACK_VTABLE_DOWNLOADPROGRESSSINK
void uniffi_wick_ffi_fn_init_callback_vtable_downloadprogresssink(const UniffiVTableCallbackInterfaceDownloadProgressSink* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_DOWNLOADPROGRESSSINK_ON_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_DOWNLOADPROGRESSSINK_ON_PROGRESS
void uniffi_wick_ffi_fn_method_downloadprogresssink_on_progress(uint64_t ptr, RustBuffer url, uint64_t bytes_downloaded, RustBuffer total_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_MODALITYSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_MODALITYSINK
uint64_t uniffi_wick_ffi_fn_clone_modalitysink(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_MODALITYSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_MODALITYSINK
void uniffi_wick_ffi_fn_free_modalitysink(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_INIT_CALLBACK_VTABLE_MODALITYSINK
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_INIT_CALLBACK_VTABLE_MODALITYSINK
void uniffi_wick_ffi_fn_init_callback_vtable_modalitysink(const UniffiVTableCallbackInterfaceModalitySink* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_TEXT_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_TEXT_TOKENS
void uniffi_wick_ffi_fn_method_modalitysink_on_text_tokens(uint64_t ptr, RustBuffer tokens, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_AUDIO_FRAMES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_AUDIO_FRAMES
void uniffi_wick_ffi_fn_method_modalitysink_on_audio_frames(uint64_t ptr, RustBuffer pcm, uint32_t sample_rate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_DONE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_MODALITYSINK_ON_DONE
void uniffi_wick_ffi_fn_method_modalitysink_on_done(uint64_t ptr, RustBuffer reason, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_SESSION
uint64_t uniffi_wick_ffi_fn_clone_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_SESSION
void uniffi_wick_ffi_fn_free_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_APPEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_APPEND_TEXT
void uniffi_wick_ffi_fn_method_session_append_text(uint64_t ptr, RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_APPEND_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_APPEND_TOKENS
void uniffi_wick_ffi_fn_method_session_append_tokens(uint64_t ptr, RustBuffer tokens, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_CANCEL
void uniffi_wick_ffi_fn_method_session_cancel(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_CAPABILITIES
RustBuffer uniffi_wick_ffi_fn_method_session_capabilities(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE
RustBuffer uniffi_wick_ffi_fn_method_session_generate(uint64_t ptr, RustBuffer opts, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_ASYNC
uint64_t uniffi_wick_ffi_fn_method_session_generate_async(uint64_t ptr, RustBuffer opts
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_STREAMING
RustBuffer uniffi_wick_ffi_fn_method_session_generate_streaming(uint64_t ptr, RustBuffer opts, uint64_t sink, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_STREAMING_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_GENERATE_STREAMING_ASYNC
uint64_t uniffi_wick_ffi_fn_method_session_generate_streaming_async(uint64_t ptr, RustBuffer opts, uint64_t sink
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_POSITION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_POSITION
uint32_t uniffi_wick_ffi_fn_method_session_position(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_RESET
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_SESSION_RESET
void uniffi_wick_ffi_fn_method_session_reset(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_WICKENGINE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CLONE_WICKENGINE
uint64_t uniffi_wick_ffi_fn_clone_wickengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_WICKENGINE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FREE_WICKENGINE
void uniffi_wick_ffi_fn_free_wickengine(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID
uint64_t uniffi_wick_ffi_fn_constructor_wickengine_from_bundle_id(RustBuffer bundle_id, RustBuffer quant, RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID_ASYNC
uint64_t uniffi_wick_ffi_fn_constructor_wickengine_from_bundle_id_async(RustBuffer bundle_id, RustBuffer quant, RustBuffer config
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_PATH
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_CONSTRUCTOR_WICKENGINE_FROM_PATH
uint64_t uniffi_wick_ffi_fn_constructor_wickengine_from_path(RustBuffer path, RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_CAPABILITIES
RustBuffer uniffi_wick_ffi_fn_method_wickengine_capabilities(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_METADATA
RustBuffer uniffi_wick_ffi_fn_method_wickengine_metadata(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_NEW_SESSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_METHOD_WICKENGINE_NEW_SESSION
uint64_t uniffi_wick_ffi_fn_method_wickengine_new_session(uint64_t ptr, RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FUNC_WICK_FFI_VERSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_FN_FUNC_WICK_FFI_VERSION
RustBuffer uniffi_wick_ffi_fn_func_wick_ffi_version(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_wick_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_wick_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_FREE
void ffi_wick_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_wick_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U8
void ffi_wick_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U8
void ffi_wick_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U8
void ffi_wick_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_wick_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I8
void ffi_wick_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I8
void ffi_wick_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I8
void ffi_wick_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_wick_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U16
void ffi_wick_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U16
void ffi_wick_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U16
void ffi_wick_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_wick_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I16
void ffi_wick_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I16
void ffi_wick_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I16
void ffi_wick_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_wick_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U32
void ffi_wick_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U32
void ffi_wick_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U32
void ffi_wick_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_wick_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I32
void ffi_wick_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I32
void ffi_wick_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I32
void ffi_wick_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_wick_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_U64
void ffi_wick_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_U64
void ffi_wick_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_U64
void ffi_wick_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_wick_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_I64
void ffi_wick_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_I64
void ffi_wick_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_I64
void ffi_wick_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_wick_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_F32
void ffi_wick_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_F32
void ffi_wick_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_F32
void ffi_wick_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_wick_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_F64
void ffi_wick_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_F64
void ffi_wick_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_F64
void ffi_wick_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_wick_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_wick_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_wick_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_wick_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_wick_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_POLL_VOID
void ffi_wick_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_wick_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_FREE_VOID
void ffi_wick_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_WICK_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_wick_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_FUNC_WICK_FFI_VERSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_FUNC_WICK_FFI_VERSION
uint16_t uniffi_wick_ffi_checksum_func_wick_ffi_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_BUNDLEREPO_STORE_DIR
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_BUNDLEREPO_STORE_DIR
uint16_t uniffi_wick_ffi_checksum_method_bundlerepo_store_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_DOWNLOADPROGRESSSINK_ON_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_DOWNLOADPROGRESSSINK_ON_PROGRESS
uint16_t uniffi_wick_ffi_checksum_method_downloadprogresssink_on_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_TEXT_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_TEXT_TOKENS
uint16_t uniffi_wick_ffi_checksum_method_modalitysink_on_text_tokens(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_AUDIO_FRAMES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_AUDIO_FRAMES
uint16_t uniffi_wick_ffi_checksum_method_modalitysink_on_audio_frames(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_DONE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_MODALITYSINK_ON_DONE
uint16_t uniffi_wick_ffi_checksum_method_modalitysink_on_done(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_APPEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_APPEND_TEXT
uint16_t uniffi_wick_ffi_checksum_method_session_append_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_APPEND_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_APPEND_TOKENS
uint16_t uniffi_wick_ffi_checksum_method_session_append_tokens(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_CANCEL
uint16_t uniffi_wick_ffi_checksum_method_session_cancel(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_CAPABILITIES
uint16_t uniffi_wick_ffi_checksum_method_session_capabilities(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE
uint16_t uniffi_wick_ffi_checksum_method_session_generate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_ASYNC
uint16_t uniffi_wick_ffi_checksum_method_session_generate_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_STREAMING
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_STREAMING
uint16_t uniffi_wick_ffi_checksum_method_session_generate_streaming(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_STREAMING_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_GENERATE_STREAMING_ASYNC
uint16_t uniffi_wick_ffi_checksum_method_session_generate_streaming_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_POSITION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_POSITION
uint16_t uniffi_wick_ffi_checksum_method_session_position(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_RESET
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_SESSION_RESET
uint16_t uniffi_wick_ffi_checksum_method_session_reset(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_CAPABILITIES
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_CAPABILITIES
uint16_t uniffi_wick_ffi_checksum_method_wickengine_capabilities(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_METADATA
uint16_t uniffi_wick_ffi_checksum_method_wickengine_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_NEW_SESSION
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_METHOD_WICKENGINE_NEW_SESSION
uint16_t uniffi_wick_ffi_checksum_method_wickengine_new_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_BUNDLEREPO_NEW
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_BUNDLEREPO_NEW
uint16_t uniffi_wick_ffi_checksum_constructor_bundlerepo_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_BUNDLEREPO_WITH_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_BUNDLEREPO_WITH_PROGRESS
uint16_t uniffi_wick_ffi_checksum_constructor_bundlerepo_with_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID
uint16_t uniffi_wick_ffi_checksum_constructor_wickengine_from_bundle_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_BUNDLE_ID_ASYNC
uint16_t uniffi_wick_ffi_checksum_constructor_wickengine_from_bundle_id_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_PATH
#define UNIFFI_FFIDEF_UNIFFI_WICK_FFI_CHECKSUM_CONSTRUCTOR_WICKENGINE_FROM_PATH
uint16_t uniffi_wick_ffi_checksum_constructor_wickengine_from_path(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_WICK_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_WICK_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_wick_ffi_uniffi_contract_version(void
    
);
#endif

